### PR TITLE
Make EVSE mockable and add mock

### PR DESCRIPTION
**Pull request by christopher-davis-afs**
## Describe your changes

This set of changes makes EVSE derived from an interface similar to what we did with ComponentStateManager,
and adds a mock to our set of mocks for v201.

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

### CODE REVIEW

**Comment by christopher-davis-afs** [comment]
CC: @shankari

**Review by shankari — APPROVED** [review]

**Review by Pietfried — CHANGES_REQUESTED** [review]
It looks like after a rebase you need to also update

`std::map<int32_t, std::unique_ptr<Evse>>& evses;`
and 
`explicit SmartChargingHandler(std::map<int32_t, std::unique_ptr<Evse>>& evses);`.

and change the the `EvseInterface` type

Except for me this looks good!

**Comment by christopher-davis-afs** [comment]
> It looks like after a rebase you need to also update
> 
> `std::map<int32_t, std::unique_ptr<Evse>>& evses;` and `explicit SmartChargingHandler(std::map<int32_t, std::unique_ptr<Evse>>& evses);`.
> 
> and change the the `EvseInterface` type
> 
> Except for me this looks good!

Updated :)

**Review by Pietfried — APPROVED** [review]
:+1:

**Comment by drmrd** [comment]
Contributes to #361

**Pull request merged**
