### PR TITLE
Improve readability/informativeness of the OCPP 2.0.1 status document

### PR DESCRIPTION
**Pull request by drmrd**
## Describe your changes
I've made a number of improvements to the clarity and readability of the OCPP 2.0.1 status document, with the goals of making the document (a) more readable outside of GitHub (especially as plaintext) and (b) contain more informative functional requirement statuses. The changes include:

- Spacing improvements between section headers and tables
- Some light copy editing of remarks
- Reformatting tables for readability
- Expanding the legend at the top of the document to support more informative functional requirement statuses
- Updating all tables to take advantage of the new legend
- Removing remarks made redundant by the new statuses

## Issue ticket number and link
No issue.

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] If OCPP 2.0.1: I have updated the [OCPP 2.0.1 status document](https://github.com/EVerest/libocpp/tree/main/doc/ocpp_201_status.md)
- [x] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

### CODE REVIEW

**Comment by drmrd** [comment]
@shankari: For your awareness. Feel free to review.

**Comment by Pietfried** [comment]
Hi @drmrd , thanks for improving the status document for v201! Can you resolve the conflicts so we can move forward with this one?

**Review by Pietfried — APPROVED** [review]
Thanks!

Just my personal impression:
The ⛔️ for `Not Applicable` bothers me a little since it creates an initial negative effect and could cause some people who scroll down too quickly to think that the FR would not be implemented. 

Maybe that would be less of a deterrent: :negative_squared_cross_mark:

**Comment by drmrd** [comment]
You've shown me a new emoji, @Pietfried! 😄 I agree and just changed from ⛔️ to ❎ in a new commit.

**Review by Pietfried — APPROVED** [review]

**Comment by drmrd** [comment]
@Pietfried: Thanks for the review! Feel free to merge.

**Pull request merged**
