### PR TITLE
Add schedule validation

### PR DESCRIPTION
**Pull request by christopher-davis-afs**
## Describe your changes

~~Depends on #452~~ Ready now that #452 is merged :)

Implements:

* K01.FR.19
* K01.FR.31
* K01.FR.35
* K01.FR.40
* K01.FR.41

Does not implement:

* K01.FR.20
* K01.FR.34
* K01.FR.43
* K01.FR.45
* K01.FR.48

These functional requirements rely on functionality in DeviceModel, the EVSE, or message handling that is not currently implemented in Everest.

## Checklist before requesting a review

- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

### CODE REVIEW

**Review by shankari — APPROVED** [review]
No objections from a structural perspective. I spot checked some of the specifications and they seem fairly straightforward.

@drmrd @christopher-davis-afs are we tracking which of the specs are in various stages (not started, under development, in review, merged). I don't think we have an issue for each specification, and I want to make sure that they don't fall through the cracks.

**Comment by couryrr-afs** [comment]
> No objections from a structural perspective. I spot checked some of the specifications and they seem fairly straightforward.
> 
> @drmrd @christopher-davis-afs are we tracking which of the specs are in various stages (not started, under development, in review, merged). I don't think we have an issue for each specification, and I want to make sure that they don't fall through the cracks.

We are implementing a process to comprehensively track the full requirements of the specs functional blocks and their corresponding implementations status for improved visibility. Our current plan is maintaining a markdown list that shows the overall progress, with each user story containing a subsection of the list as acceptance criteria. When a story is complete the markdown will be updated.

**Comment by christopher-davis-afs** [comment]
> Looks good from my side!
> 
> Considering:
> 
>     * K01.FR.43
> 
>     * K01.FR.45
> 
>     * K01.FR.48
> 
> 
> Could we include the `SupplyPhases` from the device model for Connector, EVSE and ChargingStation to validate the schedules?

What do you mean by include here?

**Comment by Pietfried** [comment]
> > Looks good from my side!
> > Considering:
> > ```
> > * K01.FR.43
> > 
> > * K01.FR.45
> > 
> > * K01.FR.48
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Could we include the `SupplyPhases` from the device model for Connector, EVSE and ChargingStation to validate the schedules?
> 
> What do you mean by include here?

The tests could request the `SupplyPhases` variables from the device model to be able to check the precondition for K01.FR.43, K01.FR.45 and K01.FR.43 and test for the requirement definition

**Comment by christopher-davis-afs** [comment]
The preconditions for those are:

*  **K01.FR.43**: When a SetChargingProfileRequest with a value for numberPhases is received AND the EVSE is of type AC AND the Charging Station cannot ensure that no more than the received numberPhases will be used...
* **K01.FR.45**: When a SetChargingProfileRequest with a value for numberPhases is received AND the EVSE is of type AC AND the received numberPhases is NOT supported by the Charging Station and higher than the numberPhases that are supported by the Charging Station...
* **K01.FR.48**: When a SetChargingProfileRequest with a value for phaseToUse is received AND the EVSE is NOT capable of switching the phase connected to the EV, which is indicated by ACPhaseSwitchingSupported not being implemented or defined as false AND the EVSE is NOT going to use the received phaseToUse...

K01.FR.48 requires checking ACPhaseSwitchingSupported on the EVSE via DeviceModel, and as far as we can tell there's not a way to know whether or not an EVSE is of type AC or not in the current Everest codebase. We also were not able to figure out how to get a variable on a specific EVSE via DeviceModel - when we last asked about it we were told that the device model functionality was not fully hooked up in everest since we need access to the charger state machine, which is also not hooked up. So I'm a little unsure what changes to make here given the DeviceModel functionality isn't really fleshed out.

Am I misunderstanding the question? Or did I misunderstand the answer to the DeviceModel question?

**Comment by shankari** [comment]
@couryrr-afs wrt https://github.com/EVerest/libocpp/pull/521#issuecomment-1989439687 can you please add a link to the markdown to this issue once it has been generated?

**Comment by couryrr-afs** [comment]
@shankari https://github.com/US-JOET/base-camp/issues/94

**Review by Pietfried — APPROVED** [review]

**Comment by drmrd** [comment]
Contributes to #361

**Pull request merged**
