### PR TITLE
Added support for iface in libwebsockets, added config values, added …

### PR DESCRIPTION
**Pull request by AssemblyJohn**
## Describe your changes

Added the possibility of setting the used network iface for libwebsocket. Updated documentation for usage.

## Issue ticket number and link

[54](https://github.com/EVerest/libocpp/issues/542)

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have made corresponding changes to the documentation
- [x] I read the [contribution documentation](https://github.com/EVerest/EVerest/blob/main/CONTRIBUTING.md) and made sure that my changes meet its requirements

### CODE REVIEW

**Comment by marcemmers** [comment]
> It has been concluded that in the current form it serves the purpose. However, the config value will be used only as the 'default' for a network profile, if at runtime the connection manager executes an config parameter over-write, that will be the used network interface.

I would suggest to change the naming so this is also clear. Maybe something like DefaultIFace?

**Comment by AssemblyJohn** [comment]
> > It has been concluded that in the current form it serves the purpose. However, the config value will be used only as the 'default' for a network profile, if at runtime the connection manager executes an config parameter over-write, that will be the used network interface.
> 
> I would suggest to change the naming so this is also clear. Maybe something like DefaultIFace?

I am wondering if that would not create further confusion, because there is a system-wide default IFace that is used while creating any socket. Plus, it is an optional parameter, it is not required to be present in the DB, the 'rea' default is 'system-default'.

**Comment by marcemmers** [comment]
I see what you mean that that would be confusing too. Still, once we have the option to change the interface via the new functionality it is also confusing. I don't know how to improve this though so open to suggestions. Otherwise I guess we can leave it like you have it now.

**Comment by AssemblyJohn** [comment]
I'll come back after I can have a look at the network profiles PR and see how it was integrated there.

**Review by marcemmers — APPROVED** [review]

**Review by Pietfried — APPROVED** [review]

**Pull request merged**
