### PR TITLE
Check if all transctions are closed before reset waiter threat is not…

### PR DESCRIPTION
**Pull request by bWF0dGhpYXMK**
Inside handleStopTransactionResponse, it is checked, if all transcations ( Connector Number >1) are closed, before the Reset Waiter Threat is notified.

### CODE REVIEW

**Comment by Pietfried** [comment]
This looks quite similar to this PR: https://github.com/EVerest/libocpp/pull/163

**Comment by bWF0dGhpYXMK** [comment]
The major change is inside: handleStopTransactionResponse( ... ) in the end before the notify call. Assuming there are two charging sessions running. The first of the two stoptransactionResponse is called, the notify would be triggered and the reset Waiter Threat is awaked. Also there is still one charing session open? This is the change about

**Comment by Pietfried** [comment]
> The major change is inside: handleStopTransactionResponse( ... ) in the end before the notify call. Assuming there are two charging sessions running. The first of the two stoptransactionResponse is called, the notify would be triggered and the reset Waiter Threat is awaked. Also there is still one charing session open? This is the change about.
> 
> With the loop, it is checked if all charging sessions are terminated before the notify is triggered to awake the reset waiter threat.

Its fine that the reset waiter thread is awaked because it would check the condition its waiting for again and in case it is still false it would wait for the next notify or the timeout. So the part that you added to handleStopTransactionResponse is redundant

**Comment by bWF0dGhpYXMK** [comment]
Thank your for your time on that. You are right, the code is redundant. It took me a while to find this link [wait_until](https://cplusplus.com/reference/condition_variable/condition_variable/wait_until/) which describes the behavior more clearly.

**Pull request closed without merging**
