### PR TITLE
Add support for certificate links

### PR DESCRIPTION
**Pull request by mennodegraaf**
* Add support for certificate links by providing `update_certificate_links()`

### CODE REVIEW

**Comment by AssemblyJohn** [comment]
@mennodegraaf due to compatibility issues, as a feature that might not be always required, it would be best if we could have this configurable, and work for both ocpp1.6 and ocpp2.0.1. The security lib (with the exception of the GetKeyPair which will be refactored in everest-core) does not have the side-effects which libocpp can have.

**Comment by mennodegraaf** [comment]
> @mennodegraaf due to compatibility issues, as a feature that might not be always required, it would be best if we could have this configurable, and work for both ocpp1.6 and ocpp2.0.1. The security lib (with the exception of the GetKeyPair which will be refactored in everest-core) does not have the side-effects which libocpp can have.

This symlink functionality is configurable in the sense that if the symlinks are not configured nothing will be done and the functionality is as it was before.

**Comment by AssemblyJohn** [comment]
> > @mennodegraaf due to compatibility issues, as a feature that might not be always required, it would be best if we could have this configurable, and work for both ocpp1.6 and ocpp2.0.1. The security lib (with the exception of the GetKeyPair which will be refactored in everest-core) does not have the side-effects which libocpp can have.
> 
> This symlink functionality is configurable in the sense that if the symlinks are not configured nothing will be done and the functionality is as it was before.

I think it would be safer to have the function call to be configurable (if the user wants it or not), especially since it is a niche application, and there can always be side-effect. Except that, I can't find any other issues.

**Comment by mennodegraaf** [comment]
@AssemblyJohn I will it up to you if you want to prevent `update_certificate_links()` from being called with some config parameter. Note that this method will also make sure that symlinks are removed, e.g. when no certificate is valid anymore. So if symlinks are first created and then it is configured not to call the method anymore and then a certificate expires they will not be deleted.

**Review by hikinggrass — APPROVED** [review]

**Pull request merged**
